version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@semantic-release/release-notes-generator"
    versions:
    - 9.0.2
  - dependency-name: "@top-gg/sdk"
    versions:
    - 3.1.0
  - dependency-name: image-size
    versions:
    - 0.9.7
  - dependency-name: pm2
    versions:
    - 4.5.2
    - 4.5.4
    - 4.5.5
    - 4.5.6
  - dependency-name: "@semantic-release/npm"
    versions:
    - 7.0.10
    - 7.1.1
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: better-sqlite3
    versions:
    - 7.1.2
    - 7.1.4
  - dependency-name: chai
    versions:
    - 4.3.4
  - dependency-name: moment-timezone
    versions:
    - 0.5.33
  - dependency-name: canvas
    versions:
    - 2.7.0
  - dependency-name: probe-image-size
    versions:
    - 7.0.0
    - 7.0.1
  - dependency-name: nodemon
    versions:
    - 2.0.7
  - dependency-name: chartjs-node-canvas
    versions:
    - 3.0.8
    - 3.1.0
  - dependency-name: humanize-duration
    versions:
    - 3.25.1
  - dependency-name: string-similarity
    versions:
    - 4.0.4
  - dependency-name: semantic-release
    versions:
    - 17.3.7
    - 17.3.8
    - 17.3.9
    - 17.4.0
    - 17.4.1
    - 17.4.2
  - dependency-name: axios
    versions:
    - 0.21.1