require(`dotenv`).config()
const commandsLoader = require(`./src/commands/loader.js`)
const {shardLogger} = require(`./pino.config.js`)
const logger = shardLogger(`LOAD APPLICATION COMMANDS`)
const {APPLICATION_COMMANDS, GUILDONLY_COMMANDS} = commandsLoader({ logger: logger })
const applicationCommandLoader = require(`./src/commands/applicationCommandsLoader.js`)
applicationCommandLoader({ logger: logger, commands: APPLICATION_COMMANDS, guildOnly: false })
applicationCommandLoader({ logger: logger, commands: GUILDONLY_COMMANDS, guildOnly: true })