name: Release
on:
  push:
    branches: [ "master" ]
permissions:
  contents: read
jobs:
  build:
    permissions:
      contents: write 
      issues: write 
      pull-requests: write 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 24.4.1, 24.x ]
    name: Build and Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - name: Codestyle Test
        run: npm run lint:check
      - name: Unit Test
        run: npm run unit-test
          
  tag:
    name: Versioning
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    steps:
      # Checking out
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      # Setting up nodejs environment
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24.4.1
      - run: npm ci
      # Run semantic-release script
      - name: Versionize
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
