name: Get latest release
on:
    push:
        branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: keydb
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
      - name: What version
        run: echo "# Last tag used" > ${{steps.keydb.outputs.release}}
        